export const USER_ROLES = {
  ADMIN: 'ADMIN',
  MESERO: 'MESERO',
  COCINERO: 'COCINERO',
  CAJERO: 'CAJERO',
  CLIENTE: 'CLIENTE',
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const USER_ROLE_OPTIONS: UserRole[] = [
  USER_ROLES.ADMIN,
  USER_ROLES.MESERO,
  USER_ROLES.COCINERO,
  USER_ROLES.CAJERO,
  USER_ROLES.CLIENTE,
];

export const UI_TO_BACKEND_ROLE: Record<UserRole, string> = {
  ADMIN: 'ADMINISTRADOR',
  MESERO: 'MESERO',
  COCINERO: 'COCINERO',
  CAJERO: 'CAJERO',
  CLIENTE: 'CLIENTE',
};

export const BACKEND_TO_UI_ROLE: Record<string, UserRole> = {
  ADMIN: USER_ROLES.ADMIN,
  ADMINISTRADOR: USER_ROLES.ADMIN,
  MESERO: USER_ROLES.MESERO,
  COCINERO: USER_ROLES.COCINERO,
  CAJERO: USER_ROLES.CAJERO,
  CLIENTE: USER_ROLES.CLIENTE,
};